steps:
  - duration_sec: 5.0
    commands:
      - type: stop

  - repeat:
      count: 2
      steps:
      - duration_sec: 5.0
        commands:
          - type: forward
            speed: 0.5

      - duration_sec: 10.0
        commands:
          - type: backward
            speed: 0.5
            
      - duration_sec: 5.0
        commands:
          - type: forward
            speed: 0.5

  - duration_sec: 5.0
    commands:
      - type: stop
