steps:
  - duration_sec: 10.0
    commands:
      - type: stop

  - duration_sec: 10.0
    commands:
      - type: forward
        speed: 0.25

  - duration_sec: 6.0
    commands:
      - type: yaw_left
        speed: 0.25

  - duration_sec: 20.0
    commands:
      - type: forward
        speed: 0.5
      - type: yaw_left
        speed: 0.25
        
  - duration_sec: 5.0
    commands:
      - type: stop
