vars:
  pi: 3.14159265359

steps:
  - duration_sec: 10.0
    commands:
      - type: stop

  - duration_sec: 4.0
    commands:
      - type: forward
        speed: 0.5

  - duration_sec: 2.0
    commands:
      - type: yaw_left
        speed: ${pi / 4}

  - duration_sec: 20.0
    commands:
      - type: forward
        speed: ${pi / 5}
      - type: yaw_left
        speed: ${pi / 10}
        
  - duration_sec: 10.0
    commands:
      - type: stop
