vars:
  pi: 3.14159265359
  stride: 1.0
  forward_speed: 1.0
  turn_speed: ${pi / 2}

steps:
  - duration_sec: 5.0
    commands:
      - type: stop

  - repeat:
      count: 10
      steps:
        - duration_sec: ${stride}
          commands:
            - type: forward
              speed: ${forward_speed}

        - duration_sec: 1.0
          commands:
            - type: yaw_left
              speed: ${turn_speed}

        - duration_sec: ${stride}
          commands:
            - type: forward
              speed: ${forward_speed}

        - duration_sec: 1.0
          commands:
            - type: yaw_left
              speed: ${turn_speed}

        - set:
            stride: ${stride + 1.0}
        
  - duration_sec: 5.0
    commands:
      - type: stop
