vars:
  pi: 3.14159265359
  x: 0.0
  y: 0.0
  yaw: 0.0
  stride: 1.0
  forward_dur: 4.0
  yaw_dur: 4.0

steps:
  - duration_sec: 5.0
    commands:
      - type: stop

  - repeat:
      count: 6
      steps:
      - set:
          yaw: 90.0

      - repeat:
          count: 2
          steps:
            - set:
                x: ${x + stride}

            - duration_sec: ${forward_dur}
              move_to_pose:
                pos: ["${x}", "${y}"]

            - duration_sec: ${yaw_dur}
              move_to_pose:
                yaw: ${yaw}

            - set:
                y: ${y + stride}
                yaw: ${yaw + 90.0}

            - duration_sec: ${forward_dur}
              move_to_pose:
                pos: ["${x}", "${y}"]

            - duration_sec: ${yaw_dur}
              move_to_pose:
                yaw: ${yaw}

      - set:
          stride: ${stride + 1.0}
        
  - duration_sec: 5.0
    commands:
      - type: stop
