vars:
  pi: 3.14159265359
  stride: 2.0
  yaw_duration: 2.0
  forward_speed: 0.5
  turn_speed: ${pi / 2}

steps:
  - duration_sec: 5.0
    commands:
      - type: stop

  - repeat:
      count: 5
      steps:
        - duration_sec: ${stride}
          commands:
            - type: forward
              speed: ${forward_speed}

        - duration_sec: ${yaw_duration}
          commands:
            - type: yaw_left
              speed: ${turn_speed}

        - duration_sec: ${stride}
          commands:
            - type: forward
              speed: ${forward_speed}

        - duration_sec: ${yaw_duration}
          commands:
            - type: yaw_left
              speed: ${turn_speed}

        - set:
            stride: ${stride + 2.0}
        
  - duration_sec: 5.0
    commands:
      - type: stop
