steps:
  - duration_sec: 10.0
    commands:
      - type: stop

  - duration_sec: 10.0
    commands:
      - type: yaw_right
        speed: 0.5

  - duration_sec: 10.0
    commands:
      - type: stop
